services:
  homebridge:
    image: homebridge/homebridge:2024-11-29
    restart: always
    network_mode: host
    volumes:
      - "./homebridge:/homebridge"
      - "./heatpump-homebridge-plugin/dist:/homebridge/node_modules/heatpump-homebridge-plugin"
